/*
 * This source file was generated by the Gradle 'init' task
 */
package net.rinsuki.mcplugins.preserveinventory;

import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.plugin.java.JavaPlugin;

public class PreserveInventoryPlugin extends JavaPlugin {
    private File playersDir;
    private final Map<UUID, PlayerState> instances = new HashMap<>();

    @Override
    public void onEnable() {
        // Ensure data folder exists and initialize per-player state directory
        getDataFolder().mkdirs();
        playersDir = new File(getDataFolder(), "players");
        playersDir.mkdirs();
    }

    private synchronized PlayerState getPlayerState(Player player) {
        UUID uuid = player.getUniqueId();
        return instances.computeIfAbsent(uuid, id -> new PlayerState(id, playersDir, getLogger()));
    }

    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        if (!"preserveinventory".equalsIgnoreCase(command.getName())) {
            return false;
        }

        if (!(sender instanceof Player)) {
            sender.sendMessage("このコマンドはプレイヤーのみが実行できます。");
            return true;
        }

        Player player = (Player) sender;

        if (args.length == 0) {
            boolean enabled = getPlayerState(player).isEnabled();
            player.sendMessage("PreserveInventory: " + (enabled ? "ON" : "OFF"));
            player.sendMessage("/" + label + " on | off で切り替えできます。");
            return true;
        }

        String sub = args[0].toLowerCase();
        switch (sub) {
            case "on":
                getPlayerState(player).setEnabled(true);
                player.sendMessage("PreserveInventory を ON にしました。");
                return true;
            case "off":
                getPlayerState(player).setEnabled(false);
                player.sendMessage("PreserveInventory を OFF にしました。");
                return true;
            default:
                player.sendMessage("使い方: /" + label + " on | off");
                return true;
        }
    }

    @Override
    public List<String> onTabComplete(CommandSender sender, Command command, String alias, String[] args) {
        if (!"preserveinventory".equalsIgnoreCase(command.getName())) {
            return null;
        }
        if (args.length == 1) {
            List<String> c = new ArrayList<>();
            String prefix = args[0].toLowerCase();
            if ("on".startsWith(prefix)) c.add("on");
            if ("off".startsWith(prefix)) c.add("off");
            return c;
        }
        return List.of();
    }
}
