name: Build Subimage

on:
  push:
  pull_request:

jobs:
  build:
    permissions:
      contents: read
    strategy:
      matrix:
        subimage: &subimage
        - snapshotter
        - snapuploader
        include:
          - image: ubuntu-24.04
            arch: amd64
          - image: ubuntu-24.04-arm
            arch: arm64
    runs-on: ${{ matrix.image }}
    steps:
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      if: github.event_name != 'pull_request'
      with:
        registry: registry.gitlab.com
        username: ${{ secrets.GITLAB_USERNAME }}
        password: ${{ secrets.GITLAB_PASSWORD }}
    - name: Extract metadata for sub-image
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_IMAGE }}
      env:
        DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
    - uses: docker/build-push-action@v6
      id: push
      with:
        push: ${{ github.event_name != 'pull_request' }}
        provenance: mode=max
        sbom: true
        labels: ${{ steps.meta.outputs.labels }}
        annotations: ${{ steps.meta.outputs.annotations }}
        outputs: type=image,name=${{ secrets.DOCKER_IMAGE }},push-by-digest=true,name-canonical=true
        target: ${{ matrix.subimage }}
    - name: Export digest
      run: |
        mkdir -p ${{ runner.temp }}/digests
        digest="${{ steps.push.outputs.digest }}"
        touch "${{ runner.temp }}/digests/${digest#sha256:}"
    - name: Upload digest
      uses: actions/upload-artifact@v4
      with:
        name: digests-${{ matrix.subimage }}-${{ matrix.arch }}
        path: ${{ runner.temp }}/digests/*
        if-no-files-found: error
        retention-days: 1
  merge:
    runs-on: ubuntu-24.04
    needs: build
    if: github.event_name != 'pull_request'
    strategy:
      matrix:
        subimage: *subimage
    permissions:
      id-token: write
      attestations: write
      packages: write
    steps:
    - name: Download digests
      uses: actions/download-artifact@v4
      with:
        path: ${{ runner.temp }}/digests
        pattern: digests-${{ matrix.subimage }}-*
        merge-multiple: true
    - uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_IMAGE }}
        tags:
          type=ref,event=branch,prefix=${{ matrix.subimage }}-
      env:
        DOCKER_METADATA_ANNOTATIONS_LEVELS: index
    - uses: docker/login-action@v3
      with:
        registry: registry.gitlab.com
        username: ${{ secrets.GITLAB_USERNAME }}
        password: ${{ secrets.GITLAB_PASSWORD }}
    - name: Create manifest list and push
      working-directory: ${{ runner.temp }}/digests
      id: push
      run: |
        set -x
        args=()

        while IFS= read -r tag; do
          args+=("-t" "$tag")
        done < <(echo "$DOCKER_METADATA_OUTPUT_JSON" | jq -r '.tags[]')

        while IFS= read -r annotation; do
          args+=("--annotation" "$annotation")
        done < <(echo "$DOCKER_METADATA_OUTPUT_JSON" | jq -r '.annotations[]')

        for digest in *; do
          args+=("${{ secrets.DOCKER_IMAGE }}@sha256:$digest")
        done

        docker buildx imagetools create "${args[@]}" 2>&1 | tee ${{ runner.temp }}/imagetools.create.log
        echo "digest=$(sed -nE 's/.*pushing (sha256:[0-9a-f]{64}) to .*/\1/p' ${{ runner.temp }}/imagetools.create.log)" >> $GITHUB_OUTPUT
